### ISSUE TITLE
Crouching makes the camera lower to the ground, then snap to the proper height

### ISSUE THREAD

**Issue by Berzerkinblaze** [VictorienXP/gmod-enhanced-camera-2#35]
Gonna be borrowing the bug report format from another game to help the process.

**Describe the bug**
When crouching, the camera jitters and goes all the way to the ground before snapping to its intended position.

**When did you last experience the issue:**
Monday, ‎June ‎20, ‎2022, ‏‎3:17:10 AM EST

**To Reproduce**
1. Crouch and observe the bug.

**Expected behavior**
The camera would smoothly transition to the crouched position.

**Video**
https://streamable.com/3iuj1v

**Device Information**
 - Device: PC
 - OS: Windows 10
 
 **Additional context**
This bug occurs even if no other mods are enabled. In the video, it shows them starting enabled, but I only enabled them momentarily, without loading a map. The game was booted with the mods disabled.

**Comment by Norway174** [comment]
Came here to report this same issue as well.
Glad I'm not the only one. Hopefully a fix is available soon.

**Comment by NatVoltaic** [comment]
Experiencing this as well, tried clearing gmod's cache just to see if me messing around with the settings was causing it but nope, still continues
